force-app/main/default/objects/Insert_Add__c/Insert_Add__c.object-meta.xml
<CustomObject>
    <label>Insert Add</label>
    <nameField>
        <label>Add Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insert Adds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insert_Add__c/fields/Add_Id__c.field-meta.xml
<CustomField>
    <fullName>Add_Id__c</fullName>
    <displayFormat>{00000}</displayFormat>
    <label>Add ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/UserList.cls
public with sharing class UserList {
  @AuraEnabled(cacheable=true)
  public static List<Show_User__c> queryUserList() {
  
    return [
        SELECT 	User_ID__c,Id ,	Name FROM Show_User__c  ORDER BY Name
        
    ];
 
}
@AuraEnabled(cacheable=true)
  public static List<Insert_Add__c> queryAddList() {
  
    return [
        SELECT 	Add_Id__c,Id , Name FROM Insert_Add__c ORDER BY Name
        LIMIT 20
    ];
 
}
}